import {
  REACT_APP_COIN_BASE_URL,
  REACT_APP_CURRENCY_API_KEY,
  REACT_APP_CURRENCY_URL,
  REACT_APP_NEWS_API_KEY,
  REACT_APP_NEWS_BASE_URL,
} from "@env";

export default {
  REACT_APP_COIN_BASE_URL,
  REACT_APP_NEWS_BASE_URL,
  REACT_APP_NEWS_API_KEY,
  REACT_APP_CURRENCY_URL,
  REACT_APP_CURRENCY_API_KEY,
};
